name: Pull Request

on:
  pull_request:

env:
  DOCKER_BUILDX: docker/setup-buildx-action@v3
  BUILD_PUSH: docker/build-push-action@v4

jobs:
  geth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ linux/amd64, linux/arm64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: ${{ env.DOCKER_BUILDX }}

      - name: Build the Docker image
        uses: ${{ env.BUILD_PUSH }}
        with:
          context: .
          file: geth/Dockerfile
          push: false
          platforms: ${{ matrix.arch }}

  reth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: linux/amd64
            features: jemalloc, asm-keccak, optimism
          - arch: linux/arm64
            features: jemalloc, optimism
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: ${{ env.DOCKER_BUILDX }}

      - name: Build the Docker image
        uses: ${{ env.BUILD_PUSH }}
        with:
          context: .
          file: reth/Dockerfile
          push: false
          build-args: |
            FEATURES=${{ matrix.features }}
          platforms: ${{ matrix.arch }}
